name: Text Domain Updater

on:
  push:
    branches:
      - main

jobs:
  wp_textdomain_updater:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress Textdomain
      uses: varunsridharan/action-wp-textdomain@2.0
      with:
        domain: '{YOUR-TEXT-DOMAIN-HERE}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
